### ISSUE TITLE
Power User Script does not work anymore on Chromium-based browser

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/folksonomy_frontend#22] opened 2022-03-07 18:33 UTC
### Story
- Power User Script does not work anymore on Chromium-based browser
- Part of the explanation could be https://www.chromium.org/Home/chromium-security/extension-content-script-fetches/
- But this does not match temporally (I could swear it still worked in december, post chromium deprecation)

**Comment by alexgarel** [comment] 2022-03-08 08:14
Duplicate of #20

**Closed as completed by alexgarel** 2022-03-08 08:14 UTC
